#!/bin/bash
# Downloads remaining images from the live WP site. Run from repo root.
set -e
cd "$(dirname "$0")/assets/uploads"
curl -sfO "https://healthonomic.com/wp-content/uploads/june-summerheat-blog.png" || echo "FAILED: https://healthonomic.com/wp-content/uploads/june-summerheat-blog.png"
curl -sfO "https://healthonomic.com/wp-content/uploads/may-26-newsletter-banner.png" || echo "FAILED: https://healthonomic.com/wp-content/uploads/may-26-newsletter-banner.png"
curl -sfO "https://healthonomic.com/wp-content/uploads/april-26-blog.png" || echo "FAILED: https://healthonomic.com/wp-content/uploads/april-26-blog.png"
curl -sfO "https://healthonomic.com/wp-content/uploads/Healthonomic_Habit_Tracker_NoCarbPair-1.pdf" || echo "FAILED: https://healthonomic.com/wp-content/uploads/Healthonomic_Habit_Tracker_NoCarbPair-1.pdf"
curl -sfO "https://healthonomic.com/wp-content/uploads/march-blog-26.png" || echo "FAILED: https://healthonomic.com/wp-content/uploads/march-blog-26.png"
curl -sfO "https://healthonomic.com/wp-content/uploads/feb-26-blog.png" || echo "FAILED: https://healthonomic.com/wp-content/uploads/feb-26-blog.png"
curl -sfO "https://healthonomic.com/wp-content/uploads/Heart-Health-Intuition-Checklist.pdf" || echo "FAILED: https://healthonomic.com/wp-content/uploads/Heart-Health-Intuition-Checklist.pdf"
curl -sfO "https://healthonomic.com/wp-content/uploads/Gemini_Generated_Image_bbl2subbl2subbl2-e1767987362998.png" || echo "FAILED: https://healthonomic.com/wp-content/uploads/Gemini_Generated_Image_bbl2subbl2subbl2-e1767987362998.png"
curl -sfO "https://healthonomic.com/wp-content/uploads/stay-warm-during-winter.webp" || echo "FAILED: https://healthonomic.com/wp-content/uploads/stay-warm-during-winter.webp"
curl -sfO "https://healthonomic.com/wp-content/uploads/soda.webp" || echo "FAILED: https://healthonomic.com/wp-content/uploads/soda.webp"
curl -sfO "https://healthonomic.com/wp-content/uploads/mobile-scrolling.webp" || echo "FAILED: https://healthonomic.com/wp-content/uploads/mobile-scrolling.webp"
curl -sfO "https://healthonomic.com/wp-content/uploads/sunscreen.webp" || echo "FAILED: https://healthonomic.com/wp-content/uploads/sunscreen.webp"
curl -sfO "https://healthonomic.com/wp-content/uploads/doctor-with-patient.webp" || echo "FAILED: https://healthonomic.com/wp-content/uploads/doctor-with-patient.webp"
curl -sfO "https://healthonomic.com/wp-content/uploads/blood-pressure-monitoring.webp" || echo "FAILED: https://healthonomic.com/wp-content/uploads/blood-pressure-monitoring.webp"
curl -sfO "https://healthonomic.com/wp-content/uploads/health-checking.webp" || echo "FAILED: https://healthonomic.com/wp-content/uploads/health-checking.webp"
curl -sfO "https://healthonomic.com/wp-content/uploads/ProteinBarsIllinois.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/ProteinBarsIllinois.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/2.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/2.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/AdobeStock_241983905-1024x683.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/AdobeStock_241983905-1024x683.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/AdobeStock_229735927-1024x479.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/AdobeStock_229735927-1024x479.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/AdobeStock_249748393-1024x683.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/AdobeStock_249748393-1024x683.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/AdobeStock_79730894-1536x1019.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/AdobeStock_79730894-1536x1019.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/AdobeStock_252194497-1536x1024.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/AdobeStock_252194497-1536x1024.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/image1-1536x1024.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/image1-1536x1024.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/AdobeStock_282610448-1536x1024.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/AdobeStock_282610448-1536x1024.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/image1-1536x864.jpg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/image1-1536x864.jpg"
curl -sfO "https://healthonomic.com/wp-content/uploads/AdobeStock_151595164-1024x683.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/AdobeStock_151595164-1024x683.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/AdobeStock_302634350-1536x1023.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/AdobeStock_302634350-1536x1023.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/AdobeStock_290616592-1536x1024.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/AdobeStock_290616592-1536x1024.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/Health_357702467-1536x1023.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/Health_357702467-1536x1023.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/AdobeStock_268288215-1536x1024.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/AdobeStock_268288215-1536x1024.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/HELTHO-1-1536x772.png" || echo "FAILED: https://healthonomic.com/wp-content/uploads/HELTHO-1-1536x772.png"
curl -sfO "https://healthonomic.com/wp-content/uploads/AdobeStock_100836078-1536x1024.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/AdobeStock_100836078-1536x1024.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/AdobeStock_121790612-1536x1192.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/AdobeStock_121790612-1536x1192.jpeg"
curl -sfO "https://healthonomic.com/wp-content/uploads/AdobeStock_320398572-1536x518.jpeg" || echo "FAILED: https://healthonomic.com/wp-content/uploads/AdobeStock_320398572-1536x518.jpeg"
echo "done: $(ls | wc -l) files in assets/uploads"
